language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: LqOXppX3hqIM7OcnT9098SidOtgTlCt6kkgRMO2Y2K8DHtF+ikFI2zT44/hIRfv84D7OFbvARS1mCtZZfkrTSOto1R8j1f1plIoB1l7rR5SNIpTAdfFmQ2SwRvmdk4mqM8zLEAe4uYB4+bjHrZX8+V07mY03kR99pOKqvvnHvYq3rWj4QBGPK814ntdOUZZe83HWk/DIx/cwXxQpsbnXwOMulwnbtpHNsiTonIM7BIF05Fu97X/q4MgVSiVJAy5PNSazHsM2cnf0wVL1lV19fkuiR+hyhcRm3I2Ai1nDInbSFVmzkvGnDdgcmUfUZAzSP920bzJ2XMbiz3Pt5x/HKgBY4xZEeGSSd7hvxxQ0jh5Vss8y/lRYMwleywvvSQqYbuXJgmdty7nYZatd+RLUm9DD6yJAx6OMb7TVtWOzTVoHjdjzkZlRG+PIDG49dDreYOsAggDTIrxf0LVHt47dRIaj+pV3zI5f+fUbuohB6eyyBF1cdRojVPmZAh7wgzgxbmBX588Z4iFLLb2zxfPnXVuBl5Zd7AnT9J94QINXEvMvuQAnNPq/enYqYB7RnofFy3WRTZ7dxmFM0R9ZXIOVBVbmz5bcmycwhebkkfi0G0oEolR38wEDmkO4GxPLpH7dnedbQr539JeRAsUdtEsvkC0Di+hG7tiSezIrO4ISxx8=
  app: morning-falls-29292
